name: 5e2024

services:
  5etools:
    container_name: 5e2024
    image: ghcr.io/5etools-mirror-3/5etools-img:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - .:/var/www/localhost/htdocs/
    ports:
      - "8224:80" # where 8224 is the port on the machine and 80 is the internal port of the container. 